openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
servers:
  - url: http://localhost:4000
  - url: https://contacts-dk78.onrender.com (Постав проета посилання)
paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
